# Generated by Django 2.0.1 on 2018-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('event_start_time', models.TimeField()),
                ('event_start_date', models.DateField()),
                ('registration_start_time', models.TimeField(blank=True, null=True)),
                ('registration_start_date', models.DateField(blank=True, max_length=500, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('available_spots', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_start_date'],
            },
        ),
    ]
