# Generated by Django 2.0.1 on 2019-03-12 15:50

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='events/')),
                ('event_start_time', models.DateTimeField()),
                ('event_end_time', models.DateTimeField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_start_time', models.DateTimeField(blank=True, null=True)),
                ('alumni', models.BooleanField(default=False)),
                ('class_1', models.BooleanField(default=False)),
                ('class_2', models.BooleanField(default=False)),
                ('class_3', models.BooleanField(default=False)),
                ('class_4', models.BooleanField(default=False)),
                ('class_5', models.BooleanField(default=False)),
                ('only_komite', models.BooleanField(default=False)),
                ('available_spots', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registerd_users', to=settings.AUTH_USER_MODEL)),
                ('waiting_list', models.ManyToManyField(blank=True, related_name='waiting_list_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_start_time'],
            },
        ),
    ]
