# Generated by Django 2.2.2 on 2019-07-07 18:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190616_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='image', upload_to='events/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
