# Generated by Django 2.2.2 on 2019-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190707_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
