# Generated by Django 2.0.1 on 2018-05-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180508_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='event_start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
