# Generated by Django 2.0.1 on 2018-05-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
