# Generated by Django 2.2.24 on 2022-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210202_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expo',
            field=models.BooleanField(default=False),
        ),
    ]
