# Generated by Django 2.0.1 on 2018-05-12 10:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180511_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to='wiki/'),
            preserve_default=False,
        ),
    ]
