# Generated by Django 2.0.1 on 2018-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_year_limit',
            field=models.IntegerField(choices=[(2018, '1.klasse'), (2019, '2.klasse')], default=2020, verbose_name='Klasse'),
        ),
    ]
