# Generated by Django 2.0.1 on 2018-09-06 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20180831_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting_list_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registerd_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_year_limit',
            field=models.IntegerField(blank=True, choices=[(1, 'Alle (inkludert alumni)'), (2023, '1. - 5. klasse'), (2022, '2. - 5. klasse'), (2021, '3. - 5. klasse'), (2020, '4. og 5. klasse'), (2019, '5. klasse')], null=True, verbose_name='Åpent for:'),
        ),
    ]
