# Generated by Django 2.0.1 on 2018-09-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180906_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='open_for',
        ),
    ]
