# Generated by Django 2.0.1 on 2018-09-20 15:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180913_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='events/'),
        ),
    ]
