# Generated by Django 2.0.1 on 2018-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180920_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='only_komite',
            field=models.BooleanField(default=False),
        ),
    ]
