# Generated by Django 2.0.1 on 2018-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_only_komite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_year_limit',
        ),
        migrations.AddField(
            model_name='event',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='class_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='class_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='class_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='class_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='class_5',
            field=models.BooleanField(default=False),
        ),
    ]
