# Generated by Django 2.0.1 on 2018-03-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateNewPost',
            new_name='Article',
        ),
    ]
