# Generated by Django 2.0.1 on 2018-03-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180304_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='paragraph',
            new_name='text',
        ),
    ]
