# Generated by Django 2.0.1 on 2018-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180511_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='FYI', max_length=10),
            preserve_default=False,
        ),
    ]
