# Generated by Django 2.0.1 on 2018-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20180511_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
