# Generated by Django 2.0.1 on 2018-05-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20180511_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('FYI', 'FYI'), ('LOL', 'LOL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/'),
        ),
    ]
