# Generated by Django 2.0.1 on 2018-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_remove_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='body_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
