# Generated by Django 2.0.1 on 2018-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_auto_20180804_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
