# Generated by Django 2.0.1 on 2018-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20180805_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-visits', 'title']},
        ),
        migrations.AlterField(
            model_name='article',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
