# Generated by Django 2.0.1 on 2018-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20180805_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
