# Generated by Django 2.0.1 on 2018-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_auto_20180826_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
