# Generated by Django 2.0.1 on 2018-08-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20180831_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='created',
        ),
    ]
