# Generated by Django 2.0.1 on 2018-08-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20180831_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
