# Generated by Django 2.0.1 on 2018-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_auto_20180831_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
