# Generated by Django 2.0.1 on 2018-09-20 15:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180826_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='projectimages/'),
        ),
    ]
