# Generated by Django 2.0.1 on 2019-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190404_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-year', '-semester'), 'verbose_name': 'Prosjekt', 'verbose_name_plural': 'Prosjekter'},
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('Høst', 'Høst'), ('Vår', 'Vår')], default='Høst', max_length=5),
        ),
    ]
