# Generated by Django 2.2.2 on 2019-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190519_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-class_year', 'course'), 'verbose_name': 'Prosjekt', 'verbose_name_plural': 'Prosjekter'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AddField(
            model_name='project',
            name='class_year',
            field=models.IntegerField(choices=[('1. klasse', '1. klasse'), ('2. klasse', '2. klasse'), ('3. klasse', '3. klasse'), ('4. klasse', '4. klasse'), ('5. klasse', '5. klasse')], default=2019, verbose_name='Klasse'),
        ),
    ]
