# Generated by Django 2.2.2 on 2019-07-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190716_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('creation_date', 'title'), 'verbose_name': 'Prosjekt', 'verbose_name_plural': 'Prosjekter'},
        ),
    ]
