# Generated by Django 2.2.2 on 2019-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190716_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_year',
            field=models.CharField(choices=[('1. klasse', '1. klasse'), ('2. klasse', '2. klasse'), ('3. klasse', '3. klasse'), ('4. klasse', '4. klasse'), ('5. klasse', '5. klasse')], max_length=10, verbose_name='Klasse'),
        ),
    ]
