# Generated by Django 2.2.2 on 2019-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190716_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_year',
            field=models.CharField(blank=True, choices=[('1. klasse', '1. klasse'), ('2. klasse', '2. klasse'), ('3. klasse', '3. klasse'), ('4. klasse', '4. klasse'), ('5. klasse', '5. klasse')], max_length=10, null=True, verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
