# Generated by Django 2.2.2 on 2019-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190728_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='tittel', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
