# Generated by Django 2.2.2 on 2019-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190728_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
