# Generated by Django 2.2.2 on 2019-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190728_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('creation_date',), 'verbose_name': 'Prosjekt', 'verbose_name_plural': 'Prosjekter'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
