# Generated by Django 2.2.2 on 2019-07-29 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190728_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('creation_date',), 'verbose_name': 'Prosjektbilde', 'verbose_name_plural': 'Prosjektbilder'},
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='order',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
