# Generated by Django 2.2.2 on 2019-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190729_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Prosjekt', 'verbose_name_plural': 'Prosjekter'},
        ),
    ]
