# Generated by Django 2.0.1 on 2019-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_year',
            field=models.CharField(choices=[('1.klasse', '1.klasse'), ('2.klasse', '2.klasse'), ('3.klasse', '3.klasse'), ('4.klasse', '4.klasse'), ('5.klasse', '5.klasse'), ('Ikke trinnavhengig', 'Ikke trinnavhengig')], default='Ikke trinnavhengig', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='display_without_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='course.CourseReview'),
        ),
    ]
