# Generated by Django 2.2.2 on 2019-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printingqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='gcode',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
