# Generated by Django 2.2.2 on 2019-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='title',
            field=models.CharField(default='Heisann', max_length=300),
            preserve_default=False,
        ),
    ]
