# Generated by Django 2.2.2 on 2019-06-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.Tip')),
            ],
        ),
    ]
