# Generated by Django 2.2.2 on 2019-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
