# Generated by Django 2.0.1 on 2019-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursereview_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_year',
            field=models.CharField(choices=[('1.klasse', '1.klasse'), ('2.klasse', '2.klasse'), ('3.klasse', '3.klasse'), ('4.klasse', '4.klasse'), ('5.klasse', '5.klasse'), ('Ikke trinnavhengig', 'Ikke trinnavhengig')], default='Ikke trinnavhengig', max_length=20),
        ),
    ]
