# Generated by Django 2.2.1 on 2019-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190312_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='filter',
            field=models.ManyToManyField(blank=True, to='courses.CourseFilter'),
        ),
    ]
