# Generated by Django 2.2.1 on 2019-05-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190520_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='filter',
        ),
    ]
