# Generated by Django 2.0.1 on 2019-02-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190223_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselink',
            name='title',
        ),
    ]
