# Generated by Django 2.0.1 on 2019-02-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_courselink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='links',
        ),
        migrations.AddField(
            model_name='courselink',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
