# Generated by Django 2.0.1 on 2019-02-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190223_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='courselink',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='author',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseLink',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
