# Generated by Django 2.0.1 on 2019-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190223_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_year',
            field=models.CharField(choices=[('1.klasse', '1.klasse'), ('2.klasse', '2.klasse'), ('3.klasse', '3.klasse'), ('4.klasse', '4.klasse'), ('5.klasse', '5.klasse'), ('Ikke trinnavhengig', 'Ikke trinnavhengig')], default='Udefinert', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='courses.CourseReview'),
        ),
    ]
