# Generated by Django 2.0.1 on 2019-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190304_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='display_without_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='courses.CourseReview'),
        ),
    ]
