# Generated by Django 2.0.1 on 2019-02-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190223_1658'),
        ('courses', '0009_auto_20190223_1645'),
    ]

    operations = [
    ]
