# Generated by Django 2.0.1 on 2018-09-09 08:53

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180906_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[authentication.validators.validate_stud_email], verbose_name='email address'),
        ),
    ]
