# Generated by Django 2.0.1 on 2018-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180909_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(choices=[(2023, '1.klasse'), (2022, '2.klasse'), (2021, '3.klasse'), (2020, '4.klasse'), (2019, '5.klasse'), (5000, 'Alumni')], verbose_name='Klasse'),
        ),
    ]
