# Generated by Django 2.0.1 on 2018-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180913_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_komite',
            field=models.BooleanField(default=False),
        ),
    ]
