# Generated by Django 2.2.2 on 2020-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190809_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(choices=[(2025, '1.klasse'), (2024, '2.klasse'), (2023, '3.klasse'), (2022, '4.klasse'), (2021, '5.klasse'), (5000, 'Alumni')], verbose_name='Klasse'),
        ),
    ]
