# Generated by Django 2.2.2 on 2021-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20201006_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(choices=[(2026, '1.klasse'), (2025, '2.klasse'), (2024, '3.klasse'), (2023, '4.klasse'), (2022, '5.klasse'), (5000, 'Alumni')], verbose_name='Klasse'),
        ),
    ]
