# Generated by Django 4.1.1 on 2022-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210901_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(choices=[(2027, '1.klasse'), (2026, '2.klasse'), (2025, '3.klasse'), (2024, '4.klasse'), (2023, '5.klasse'), (5000, 'Alumni')], verbose_name='Klasse'),
        ),
    ]
