# Generated by Django 2.0.1 on 2018-07-23 20:22

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Styremedlem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styretittel', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('e_mail', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('profile_picture', imagekit.models.fields.ProcessedImageField(upload_to='styremedlem/')),
            ],
            options={
                'verbose_name': 'Styremedlem',
                'verbose_name_plural': 'Styremedlemmer',
            },
        ),
    ]
