# Generated by Django 2.0.1 on 2018-07-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_komiteer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komiteer',
            options={'verbose_name': 'Komité', 'verbose_name_plural': 'Komiteer'},
        ),
    ]
