# Generated by Django 2.0.1 on 2018-07-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_nyhet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nyhet',
            options={'verbose_name': 'Nyhet', 'verbose_name_plural': 'Nyheter'},
        ),
    ]
