# Generated by Django 2.0.1 on 2019-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180723_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_deadline', models.DateTimeField()),
                ('job_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Stillingsannonse',
                'verbose_name_plural': 'Stillingsannonser',
            },
        ),
    ]
