# Generated by Django 2.0.1 on 2019-03-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobb',
        ),
    ]
