# Generated by Django 2.2.2 on 2019-06-29 10:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_jobb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komiteer',
            old_name='komite',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='komiteer',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='komiteer/'),
        ),
    ]
