# Generated by Django 2.2.2 on 2019-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190629_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('year', models.PositiveIntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Nyhet',
        ),
    ]
