# Generated by Django 2.2.2 on 2019-06-29 17:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190629_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesign',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='events/'),
            preserve_default=False,
        ),
    ]
