# Generated by Django 2.2.2 on 2019-07-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190721_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komiteer',
            old_name='post_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='komiteer',
            old_name='post_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='komiteer',
            old_name='post_title',
            new_name='title',
        ),
    ]
