# Generated by Django 2.2.2 on 2019-07-22 18:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesign',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='komite/'),
        ),
    ]
