# Generated by Django 2.2.2 on 2019-09-02 09:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0004_auto_20190728_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontaktperson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='komite/')),
                ('email', models.PositiveIntegerField()),
            ],
        ),
    ]
