# Generated by Django 2.2.2 on 2019-09-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0005_kontaktperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktperson',
            name='stilling',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
