# Generated by Django 2.2.2 on 2019-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0006_kontaktperson_stilling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontaktperson',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
