# Generated by Django 2.2.2 on 2020-10-22 13:54

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0009_auto_20201006_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nyheter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='nyheter/')),
                ('slug', models.SlugField(blank=True, max_length=60)),
            ],
        ),
    ]
