# Generated by Django 2.2.2 on 2020-11-09 14:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0011_auto_20201022_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nyhet',
            options={'ordering': ['-post_time', 'title'], 'verbose_name': 'Nyhet', 'verbose_name_plural': 'Nyheter'},
        ),
        migrations.AddField(
            model_name='kontaktperson',
            name='hoverImage',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='komite/'),
        ),
    ]
