# Generated by Django 2.2.2 on 2021-09-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0014_auto_20210601_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nyhet',
            old_name='external_link',
            new_name='external_link_1',
        ),
        migrations.RenameField(
            model_name='nyhet',
            old_name='link_text',
            new_name='link_text_1',
        ),
        migrations.AddField(
            model_name='nyhet',
            name='external_link_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nyhet',
            name='external_link_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nyhet',
            name='link_text_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nyhet',
            name='link_text_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
