# Generated by Django 2.2.24 on 2021-10-15 12:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('leonardo', '0015_auto_20211015_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyhet',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
