# Generated by Django 2.0.1 on 2019-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_deadline', models.DateTimeField()),
                ('job_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Stillingsannonse',
                'verbose_name_plural': 'Stillingsannonser',
            },
        ),
    ]
