# Generated by Django 2.2.2 on 2019-08-19 17:15

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190315_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(null=True, upload_to='komite/')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be a hex code', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
            ],
        ),
    ]
