# Generated by Django 2.2.2 on 2019-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Bekk', max_length=100),
            preserve_default=False,
        ),
    ]
