# Generated by Django 2.2.2 on 2020-10-21 12:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20190820_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='job/'),
        ),
    ]
