# Generated by Django 2.2.2 on 2021-02-01 16:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hyperlink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hyperlinkText',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='job/'),
        ),
    ]
