# Generated by Django 2.2.2 on 2021-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210201_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='hyperlink',
            new_name='external_link_1',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='hyperlinkText',
            new_name='link_text_1',
        ),
        migrations.AddField(
            model_name='job',
            name='external_link_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_link_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='link_text_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='link_text_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
