# Generated by Django 2.2.24 on 2021-10-15 10:43

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20210910_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
