# Generated by Django 2.2.2 on 2020-11-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190728_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_start_time', 'title'], 'verbose_name': 'Arrangement', 'verbose_name_plural': 'Arrangementer'},
        ),
    ]
