# Generated by Django 2.2.2 on 2021-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201109_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
